### PR TITLE
sqlite_connector should catch import errors just like the other conne…

### PR DESCRIPTION
**Pull request by kdriedger-simutech**
Both mysql connector and prostgress connector have a try/except around the import, it seems that sqlite ought to as well.

### CODE REVIEW

**Comment by sdispater** [comment]
`sqlite3` is a standard library in both python 2.7 and python 3.2+ which are the only python versions supported, so I don't think this is necessary. But I may be wrong.

Have you encountered an import error for sqlite?

**Comment by kdriedger-simutech** [comment]
Yes, I experienced a bug.

Where would this library be?   If I do a: “pip list” I don’t see sqlite.  I do see it in \python27\Lib\sqlite3

Hmmm.  Could be it’s because I’m using the Google App Engine Python and it doesn’t use the Lib directory in order to run python?

**Comment by sdispater** [comment]
Yes, the error might be related to the Google App Engine.

**Comment by sdispater** [comment]
I merged your pull request since it's likely that other people will encounter this error.

**Pull request merged**
