### PR TITLE
Retrieve mysql server version from itself

### PR DESCRIPTION
**Pull request by gdraynz**

### CODE REVIEW

**Comment by sdispater** [comment]
I guess this is for compatibility between the various dbapi implementations for MySQL.

So maybe we could use the `get_server_info()` method which exists for both `PyMySQL` and `mysqlclient` and returns the MySQL version.

**Comment by sdispater** [comment]
Also the members of the version tuple must be integers (for comparison)

**Comment by gdraynz** [comment]
Ah! I may have submitted this a bit too fast, but I stumbled upon an attribute error here that I had to bypass here.
```
AttributeError: 'Connection' object has no attribute '_server_version'
```

**Comment by sdispater** [comment]
Yes, the `_server_version` attribute exists only for `mysqlclient`. I will probably add tests to cover `PYMySQL`.

**Pull request merged**
