### PR TITLE
 Avoid sqlite constraint collision

### PR DESCRIPTION
**Pull request by ihumanable**
```
SQLite version 3.8.5 2014-08-15 22:37:57
    Enter ".help" for usage hints.
    sqlite> .headers on
    sqlite> .mode column
    sqlite> PRAGMA foreign_key_list ('test_table');
    id          seq         table       from        to          on_update   on_delete   match
    ----------  ----------  ----------  ----------  ----------  ----------  ----------  ----------
```

### CODE REVIEW

**Comment by ihumanable** [comment]
This addresses a bug that occurs when an Orator migration attempts to copy a sqlite table that has multiple foreign keys.  (These operations occur when a migration attempts to simulate functionality that sqlite does not natively support, ex: drop a column)

In the previous version of the code, it attempts to use a field called `constraint_name` from the result of calling `PRAGMA foreign_key_list('{table}')`.  On some versions of sqlite (See the description for an example from version 3.8.5) there is no such column returned from the `foreign_key_list` pragma.

This error causes all the foreign keys on the table being copied to be merged into a single foreign key, which will almost always cause the migration to fail.

This PR fixes this behavior by attempting to use `constraint_name` if available, if not available it synthesizes a new constraint name based off of the `from`_`table`_`to` values returned by the pragma.

**Comment by dougblack** [comment]
👍

**Comment by sdispater** [comment]
Thanks for catching this 👏 

However, after checking it out, it seems that the underlying problem is that when creating a table with SQLite, Orator does not set the name of the constraint, therefore the `constraint_name` column is missing.

I will investigate further and get back to you.

**Comment by sdispater** [comment]
So, it seems that SQLite does not support setting a constraint name (well, you can setting one but the information cannot be retrieved), so your solution is probably the best.

Just a small change I would make: the table name should be first in the new foreign key name

```python
name = '%s_%s_%s' % (value['table'], value['from'], value['to'])
```
Also, if you could add a test covering this case, it would be nice 😃 The best place for it is `schema/integrations` I think. But if you don't know how to setup the test, don't worry, I will do it.

**Pull request merged**
