### PR TITLE
If mysql begin a transaction and lost connection, reconnect

### PR DESCRIPTION
**Pull request by zhanghaofei**
Fix the following problems:

````python
Traceback (most recent call last):
  File "orator_db.py", line 97, in <module>
    with db.connection('yh_edu').transaction():
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.6/site-packages/orator/connections/connection.py", line 288, in transaction
    self.begin_transaction()
  File "/usr/lib/python3.6/site-packages/orator/connections/mysql_connection.py", line 42, in begin_transaction
    self._connection.autocommit(False)
  File "/usr/lib/python3.6/site-packages/pymysql/connections.py", line 753, in autocommit
    self._send_autocommit_mode()
  File "/usr/lib/python3.6/site-packages/pymysql/connections.py", line 771, in _send_autocommit_mode
    self._read_ok_packet()
  File "/usr/lib/python3.6/site-packages/pymysql/connections.py", line 760, in _read_ok_packet
    pkt = self._read_packet()
  File "/usr/lib/python3.6/site-packages/pymysql/connections.py", line 991, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/lib/python3.6/site-packages/pymysql/connections.py", line 1037, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')
```

### CODE REVIEW

**Comment by zardilior** [comment]
Please check it, its a fix to Nonetype object has no attribute autocommit when connection becomes null 
@sdispater. A constant problem in production

**Comment by zardilior** [comment]
@sdispater  there is a pr with a fix for mysql. Should be accepted or at least checked Thanks

**Comment by xargsgrep** [comment]
@sdispater any updates on this?

**Comment by zardilior** [comment]
@sdispater don't wait for the release this is necesary

**Comment by zhanghaofei** [comment]
@sdispater @josephmancuso Urgent need to update,Thanks.
The authors no longer maintain this project?

**Comment by zardilior** [comment]
@sdispater doesn't

**Comment by josephmancuso** [comment]
Does this fix the issue everyone is having sufficiently?

**Comment by zardilior** [comment]
I patched a local version of orator and it totally did @josephmancuso

**Comment by josephmancuso** [comment]
merged

**Comment by zehauser** [comment]
@josephmancuso thank you very much for merging this fix. Could you please cut and publish a new release when you have time?

This patch is what will allow my company to move off our internal fork (😬) and back to a mainline Orator release.

**Comment by josephmancuso** [comment]
@zehauser I do not have permissions to release and it work with the CI tool @sdispater has setup.

**Comment by zehauser** [comment]
@josephmancuso Can we plead to @sdispater to cut a release when he has time? 🙂

**Comment by josephmancuso** [comment]
@zehauser I reached out directly to him. Waiting for a reply

**Comment by zardilior** [comment]
@josephmancuso how long since he last answered you? Seems he is really absent

**Comment by josephmancuso** [comment]
Screen Shot 2019-08-20 at 1 18 57 PM

**Comment by zardilior** [comment]
Thanks a lot joseph

**Comment by zehauser** [comment]
😢

**Comment by alexpdr** [comment]
Any updates on this? seems issue is still unresolved? (getting the same error)

**Pull request merged**
